options:
  lineNumbers: true
  spellcheck: true
  askImageFilename: true
  overwriteImages: true
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: true

metadata:
  postImage: images/default-logo.png