thumbnail: true
## Website's icon url.
favicon: favicon.ico

## Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

## Website's logo shown on the left of the navigation bar.
## It can either be an url to an image or a string if the following option is set.
## logo:
##   text: <logo string>
logo: images/snail.png

article:
  # Show word count and estimated reading time.
  readtime: true
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  highlight: obsidian

## Search plugin settings.
search:
  type: insight

## Share plugin settings.
#share:
##  type: default
##  install_url:

## Other plugins and their settings.
plugins:
  mathjax: true
  gallery: true
  google-analytics:
    tracking_id: UA-88902574-1
    site_verification: googledfac8b467ded7e19

## Additional navigation bar links on the right.
## Links can either be text or icon. The following link is set to be an icon link whose icon
## is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
## example of setting plain text links.
navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/ddalpange

## Links at the bottom of the page.
footer_links:
  GitHub: https://github.com/ddalpange


## Menus
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about
  Github: https://github.com/ddalpange

## Widgets
widgets:
  - recent_posts
  - category
  - archive
  # - tag
  - tagcloud
  - links


## Comment
comment:
  type: disqus
  shortname: https-ddalpange-github-com

## Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
  links:
    Github: https://github.com/ddalpange
